---
api_key: d5d351ee
development_environments:
  - development
  - test
exceptions:
  ignore:
    - CanCan::AccessDenied
    - ActionController::InvalidAuthenticityToken
    - ActionController::UnknownFormat
    - ActionDispatch::RemoteIp::IpSpoofAttackError
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError
    - ActiveRecord::PreparedStatementCacheExpired
    - I18n::InvalidLocale
    - Unicorn::ClientShutdown
    - Unauthorized
    - Forbidden
    - AgeRestricted
    - MismatchedEntries
    - CopyrightedResource
    - Net::SMTPServerBusy
    - Net::SMTPFatalError
    - Interrupt
    - Apipie::ParamMissing
    - InvalidIdError
    - InvalidParameterError
    - EmptyContentError
    - MalParser::RecordNotFound
    - BadImageError
    - Errors::NotIdentifiedByImageMagickError
    - Sidekiq::Shutdown
    - Terrapin::ExitStatusError
metrics:
  enabled: false
traces:
  enabled: false
